<template>
    <div class="vca-input">
        <vca-dropdown :label="label" :errorMsg="errorMsg" v-model="current" @input="change" :title="placeholder" ref="reference" :rules="$v.country" :options="options"/>
    </div>
</template>
<script>
import { required } from 'vuelidate/lib/validators'
export default {
    name: 'VcaCountry',
    props: {
        req: {
            type: Boolean,
            default: false
        },
        placeholder: {
            type: String,
            default: 'Default placeholder'
        },
        label: {
            type: String,
            default: 'Default label'
        },
        value: {
            type: Array
        },
        preselection: {
            type: String,
            default: null
        },
        errorMsg: {
            type: String,
            default: 'Error'
        }
    },
    created() {
      if (this.preselection !== null) {

        var value = this.options.find(element => element.value == this.preselection)
        if (value != null) {
          this.current = [value]
          this.$emit("input", this.current)
        }
      }
    },
    validations: {
        country: {
            required
        }
    },
    methods: {
        change(e) {
            this.current = e
            this.$emit("input", this.current)
            if(this.req) {
                this.$refs.reference.validate()
            }
        },
        validate () {
            if(this.req) {
                this.$refs.reference.validate()
            }
        }
    },
    data() {
        return {
            current: this.value,
            options:
            [ 
              { title: 'Afghanistan', label: 'Afghanistan', value: 'AF'}, 
              { title: 'Åland Islands', label: 'Åland Islands', value: 'AX'}, 
              { title: 'Albania', label: 'Albania', value: 'AL'}, 
              { title: 'Algeria', label: 'Algeria', value: 'DZ'}, 
              { title: 'American Samoa', label: 'American Samoa', value: 'AS'}, 
              { title: 'Andorra', label: 'Andorra', value: 'AD'}, 
              { title: 'Angola', label: 'Angola', value: 'AO'}, 
              { title: 'Anguilla', label: 'Anguilla', value: 'AI'}, 
              { title: 'Antarctica', label: 'Antarctica', value: 'AQ'}, 
              { title: 'Antigua and Barbuda', label: 'Antigua and Barbuda', value: 'AG'}, 
              { title: 'Argentina', label: 'Argentina', value: 'AR'}, 
              { title: 'Armenia', label: 'Armenia', value: 'AM'}, 
              { title: 'Aruba', label: 'Aruba', value: 'AW'}, 
              { title: 'Australia', label: 'Australia', value: 'AU'}, 
              { title: 'Austria', label: 'Austria', value: 'AT'}, 
              { title: 'Azerbaijan', label: 'Azerbaijan', value: 'AZ'}, 
              { title: 'Bahamas', label: 'Bahamas', value: 'BS'}, 
              { title: 'Bahrain', label: 'Bahrain', value: 'BH'}, 
              { title: 'Bangladesh', label: 'Bangladesh', value: 'BD'}, 
              { title: 'Barbados', label: 'Barbados', value: 'BB'}, 
              { title: 'Belarus', label: 'Belarus', value: 'BY'}, 
              { title: 'Belgium', label: 'Belgium', value: 'BE'}, 
              { title: 'Belize', label: 'Belize', value: 'BZ'}, 
              { title: 'Benin', label: 'Benin', value: 'BJ'}, 
              { title: 'Bermuda', label: 'Bermuda', value: 'BM'}, 
              { title: 'Bhutan', label: 'Bhutan', value: 'BT'}, 
              { title: 'Bolivia', label: 'Bolivia', value: 'BO'}, 
              { title: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina', value: 'BA'}, 
              { title: 'Botswana', label: 'Botswana', value: 'BW'}, 
              { title: 'Bouvet Island', label: 'Bouvet Island', value: 'BV'}, 
              { title: 'Brazil', label: 'Brazil', value: 'BR'}, 
              { title: 'British Indian Ocean Territory', label: 'British Indian Ocean Territory', value: 'IO'}, 
              { title: 'Brunei Darussalam', label: 'Brunei Darussalam', value: 'BN'}, 
              { title: 'Bulgaria', label: 'Bulgaria', value: 'BG'}, 
              { title: 'Burkina Faso', label: 'Burkina Faso', value: 'BF'}, 
              { title: 'Burundi', label: 'Burundi', value: 'BI'}, 
              { title: 'Cambodia', label: 'Cambodia', value: 'KH'}, 
              { title: 'Cameroon', label: 'Cameroon', value: 'CM'}, 
              { title: 'Canada', label: 'Canada', value: 'CA'}, 
              { title: 'Cape Verde', label: 'Cape Verde', value: 'CV'}, 
              { title: 'Cayman Islands', label: 'Cayman Islands', value: 'KY'}, 
              { title: 'Central African Republic', label: 'Central African Republic', value: 'CF'}, 
              { title: 'Chad', label: 'Chad', value: 'TD'}, 
              { title: 'Chile', label: 'Chile', value: 'CL'}, 
              { title: 'China', label: 'China', value: 'CN'}, 
              { title: 'Christmas Island', label: 'Christmas Island', value: 'CX'}, 
              { title: 'Cocos (Keeling) Islands', label: 'Cocos (Keeling) Islands', value: 'CC'}, 
              { title: 'Colombia', label: 'Colombia', value: 'CO'}, 
              { title: 'Comoros', label: 'Comoros', value: 'KM'}, 
              { title: 'Congo', label: 'Congo', value: 'CG'}, 
              { title: 'Congo, The Democratic Republic of the', label: 'Congo, The Democratic Republic of the', value: 'CD'}, 
              { title: 'Cook Islands', label: 'Cook Islands', value: 'CK'}, 
              { title: 'Costa Rica', label: 'Costa Rica', value: 'CR'}, 
              { title: 'Cote D\'Ivoire', label: 'Cote D\'Ivoire', value: 'CI'}, 
              { title: 'Croatia', label: 'Croatia', value: 'HR'}, 
              { title: 'Cuba', label: 'Cuba', value: 'CU'}, 
              { title: 'Cyprus', label: 'Cyprus', value: 'CY'}, 
              { title: 'Czech Republic', label: 'Czech Republic', value: 'CZ'}, 
              { title: 'Denmark', label: 'Denmark', value: 'DK'}, 
              { title: 'Djibouti', label: 'Djibouti', value: 'DJ'}, 
              { title: 'Dominica', label: 'Dominica', value: 'DM'}, 
              { title: 'Dominican Republic', label: 'Dominican Republic', value: 'DO'}, 
              { title: 'Ecuador', label: 'Ecuador', value: 'EC'}, 
              { title: 'Egypt', label: 'Egypt', value: 'EG'}, 
              { title: 'El Salvador', label: 'El Salvador', value: 'SV'}, 
              { title: 'Equatorial Guinea', label: 'Equatorial Guinea', value: 'GQ'}, 
              { title: 'Eritrea', label: 'Eritrea', value: 'ER'}, 
              { title: 'Estonia', label: 'Estonia', value: 'EE'}, 
              { title: 'Ethiopia', label: 'Ethiopia', value: 'ET'}, 
              { title: 'Falkland Islands (Malvinas)', label: 'Falkland Islands (Malvinas)', value: 'FK'}, 
              { title: 'Faroe Islands', label: 'Faroe Islands', value: 'FO'}, 
              { title: 'Fiji', label: 'Fiji', value: 'FJ'}, 
              { title: 'Finland', label: 'Finland', value: 'FI'}, 
              { title: 'France', label: 'France', value: 'FR'}, 
              { title: 'French Guiana', label: 'French Guiana', value: 'GF'}, 
              { title: 'French Polynesia', label: 'French Polynesia', value: 'PF'}, 
              { title: 'French Southern Territories', label: 'French Southern Territories', value: 'TF'}, 
              { title: 'Gabon', label: 'Gabon', value: 'GA'}, 
              { title: 'Gambia', label: 'Gambia', value: 'GM'}, 
              { title: 'Georgia', label: 'Georgia', value: 'GE'}, 
              { title: 'Germany', label: 'Germany', value: 'DE'}, 
              { title: 'Ghana', label: 'Ghana', value: 'GH'}, 
              { title: 'Gibraltar', label: 'Gibraltar', value: 'GI'}, 
              { title: 'Greece', label: 'Greece', value: 'GR'}, 
              { title: 'Greenland', label: 'Greenland', value: 'GL'}, 
              { title: 'Grenada', label: 'Grenada', value: 'GD'}, 
              { title: 'Guadeloupe', label: 'Guadeloupe', value: 'GP'}, 
              { title: 'Guam', label: 'Guam', value: 'GU'}, 
              { title: 'Guatemala', label: 'Guatemala', value: 'GT'}, 
              { title: 'Guernsey', label: 'Guernsey', value: 'GG'}, 
              { title: 'Guinea', label: 'Guinea', value: 'GN'}, 
              { title: 'Guinea-Bissau', label: 'Guinea-Bissau', value: 'GW'}, 
              { title: 'Guyana', label: 'Guyana', value: 'GY'}, 
              { title: 'Haiti', label: 'Haiti', value: 'HT'}, 
              { title: 'Heard Island and Mcdonald Islands', label: 'Heard Island and Mcdonald Islands', value: 'HM'}, 
              { title: 'Holy See (Vatican City State)', label: 'Holy See (Vatican City State)', value: 'VA'}, 
              { title: 'Honduras', label: 'Honduras', value: 'HN'}, 
              { title: 'Hong Kong', label: 'Hong Kong', value: 'HK'}, 
              { title: 'Hungary', label: 'Hungary', value: 'HU'}, 
              { title: 'Iceland', label: 'Iceland', value: 'IS'}, 
              { title: 'India', label: 'India', value: 'IN'}, 
              { title: 'Indonesia', label: 'Indonesia', value: 'ID'}, 
              { title: 'Iran, Islamic Republic Of', label: 'Iran, Islamic Republic Of', value: 'IR'}, 
              { title: 'Iraq', label: 'Iraq', value: 'IQ'}, 
              { title: 'Ireland', label: 'Ireland', value: 'IE'}, 
              { title: 'Isle of Man', label: 'Isle of Man', value: 'IM'}, 
              { title: 'Israel', label: 'Israel', value: 'IL'}, 
              { title: 'Italy', label: 'Italy', value: 'IT'}, 
              { title: 'Jamaica', label: 'Jamaica', value: 'JM'}, 
              { title: 'Japan', label: 'Japan', value: 'JP'}, 
              { title: 'Jersey', label: 'Jersey', value: 'JE'}, 
              { title: 'Jordan', label: 'Jordan', value: 'JO'}, 
              { title: 'Kazakhstan', label: 'Kazakhstan', value: 'KZ'}, 
              { title: 'Kenya', label: 'Kenya', value: 'KE'}, 
              { title: 'Kiribati', label: 'Kiribati', value: 'KI'}, 
              { title: 'Korea, Democratic People\'S Republic of', label: 'Korea, Democratic People\'S Republic of', value: 'KP'}, 
              { title: 'Korea, Republic of', label: 'Korea, Republic of', value: 'KR'}, 
              { title: 'Kuwait', label: 'Kuwait', value: 'KW'}, 
              { title: 'Kyrgyzstan', label: 'Kyrgyzstan', value: 'KG'}, 
              { title: 'Lao People\'S Democratic Republic', label: 'Lao People\'S Democratic Republic', value: 'LA'}, 
              { title: 'Latvia', label: 'Latvia', value: 'LV'}, 
              { title: 'Lebanon', label: 'Lebanon', value: 'LB'}, 
              { title: 'Lesotho', label: 'Lesotho', value: 'LS'}, 
              { title: 'Liberia', label: 'Liberia', value: 'LR'}, 
              { title: 'Libyan Arab Jamahiriya', label: 'Libyan Arab Jamahiriya', value: 'LY'}, 
              { title: 'Liechtenstein', label: 'Liechtenstein', value: 'LI'}, 
              { title: 'Lithuania', label: 'Lithuania', value: 'LT'}, 
              { title: 'Luxembourg', label: 'Luxembourg', value: 'LU'}, 
              { title: 'Macao', label: 'Macao', value: 'MO'}, 
              { title: 'Macedonia, The Former Yugoslav Republic of', label: 'Macedonia, The Former Yugoslav Republic of', value: 'MK'}, 
              { title: 'Madagascar', label: 'Madagascar', value: 'MG'}, 
              { title: 'Malawi', label: 'Malawi', value: 'MW'}, 
              { title: 'Malaysia', label: 'Malaysia', value: 'MY'}, 
              { title: 'Maldives', label: 'Maldives', value: 'MV'}, 
              { title: 'Mali', label: 'Mali', value: 'ML'}, 
              { title: 'Malta', label: 'Malta', value: 'MT'}, 
              { title: 'Marshall Islands', label: 'Marshall Islands', value: 'MH'}, 
              { title: 'Martinique', label: 'Martinique', value: 'MQ'}, 
              { title: 'Mauritania', label: 'Mauritania', value: 'MR'}, 
              { title: 'Mauritius', label: 'Mauritius', value: 'MU'}, 
              { title: 'Mayotte', label: 'Mayotte', value: 'YT'}, 
              { title: 'Mexico', label: 'Mexico', value: 'MX'}, 
              { title: 'Micronesia, Federated States of', label: 'Micronesia, Federated States of', value: 'FM'}, 
              { title: 'Moldova, Republic of', label: 'Moldova, Republic of', value: 'MD'}, 
              { title: 'Monaco', label: 'Monaco', value: 'MC'}, 
              { title: 'Mongolia', label: 'Mongolia', value: 'MN'}, 
              { title: 'Montserrat', label: 'Montserrat', value: 'MS'}, 
              { title: 'Morocco', label: 'Morocco', value: 'MA'}, 
              { title: 'Mozambique', label: 'Mozambique', value: 'MZ'}, 
              { title: 'Myanmar', label: 'Myanmar', value: 'MM'}, 
              { title: 'Namibia', label: 'Namibia', value: 'NA'}, 
              { title: 'Nauru', label: 'Nauru', value: 'NR'}, 
              { title: 'Nepal', label: 'Nepal', value: 'NP'}, 
              { title: 'Netherlands', label: 'Netherlands', value: 'NL'}, 
              { title: 'Netherlands Antilles', label: 'Netherlands Antilles', value: 'AN'}, 
              { title: 'New Caledonia', label: 'New Caledonia', value: 'NC'}, 
              { title: 'New Zealand', label: 'New Zealand', value: 'NZ'}, 
              { title: 'Nicaragua', label: 'Nicaragua', value: 'NI'}, 
              { title: 'Niger', label: 'Niger', value: 'NE'}, 
              { title: 'Nigeria', label: 'Nigeria', value: 'NG'}, 
              { title: 'Niue', label: 'Niue', value: 'NU'}, 
              { title: 'Norfolk Island', label: 'Norfolk Island', value: 'NF'}, 
              { title: 'Northern Mariana Islands', label: 'Northern Mariana Islands', value: 'MP'}, 
              { title: 'Norway', label: 'Norway', value: 'NO'}, 
              { title: 'Oman', label: 'Oman', value: 'OM'}, 
              { title: 'Pakistan', label: 'Pakistan', value: 'PK'}, 
              { title: 'Palau', label: 'Palau', value: 'PW'}, 
              { title: 'Palestinian Territory, Occupied', label: 'Palestinian Territory, Occupied', value: 'PS'}, 
              { title: 'Panama', label: 'Panama', value: 'PA'}, 
              { title: 'Papua New Guinea', label: 'Papua New Guinea', value: 'PG'}, 
              { title: 'Paraguay', label: 'Paraguay', value: 'PY'}, 
              { title: 'Peru', label: 'Peru', value: 'PE'}, 
              { title: 'Philippines', label: 'Philippines', value: 'PH'}, 
              { title: 'Pitcairn', label: 'Pitcairn', value: 'PN'}, 
              { title: 'Poland', label: 'Poland', value: 'PL'}, 
              { title: 'Portugal', label: 'Portugal', value: 'PT'}, 
              { title: 'Puerto Rico', label: 'Puerto Rico', value: 'PR'}, 
              { title: 'Qatar', label: 'Qatar', value: 'QA'}, 
              { title: 'Reunion', label: 'Reunion', value: 'RE'}, 
              { title: 'Romania', label: 'Romania', value: 'RO'}, 
              { title: 'Russian Federation', label: 'Russian Federation', value: 'RU'}, 
              { title: 'RWANDA', label: 'RWANDA', value: 'RW'}, 
              { title: 'Saint Helena', label: 'Saint Helena', value: 'SH'}, 
              { title: 'Saint Kitts and Nevis', label: 'Saint Kitts and Nevis', value: 'KN'}, 
              { title: 'Saint Lucia', label: 'Saint Lucia', value: 'LC'}, 
              { title: 'Saint Pierre and Miquelon', label: 'Saint Pierre and Miquelon', value: 'PM'}, 
              { title: 'Saint Vincent and the Grenadines', label: 'Saint Vincent and the Grenadines', value: 'VC'}, 
              { title: 'Samoa', label: 'Samoa', value: 'WS'}, 
              { title: 'San Marino', label: 'San Marino', value: 'SM'}, 
              { title: 'Sao Tome and Principe', label: 'Sao Tome and Principe', value: 'ST'}, 
              { title: 'Saudi Arabia', label: 'Saudi Arabia', value: 'SA'}, 
              { title: 'Senegal', label: 'Senegal', value: 'SN'}, 
              { title: 'Serbia and Montenegro', label: 'Serbia and Montenegro', value: 'CS'}, 
              { title: 'Seychelles', label: 'Seychelles', value: 'SC'}, 
              { title: 'Sierra Leone', label: 'Sierra Leone', value: 'SL'}, 
              { title: 'Singapore', label: 'Singapore', value: 'SG'}, 
              { title: 'Slovakia', label: 'Slovakia', value: 'SK'}, 
              { title: 'Slovenia', label: 'Slovenia', value: 'SI'}, 
              { title: 'Solomon Islands', label: 'Solomon Islands', value: 'SB'}, 
              { title: 'Somalia', label: 'Somalia', value: 'SO'}, 
              { title: 'South Africa', label: 'South Africa', value: 'ZA'}, 
              { title: 'South Georgia and the South Sandwich Islands', label: 'South Georgia and the South Sandwich Islands', value: 'GS'}, 
              { title: 'Spain', label: 'Spain', value: 'ES'}, 
              { title: 'Sri Lanka', label: 'Sri Lanka', value: 'LK'}, 
              { title: 'Sudan', label: 'Sudan', value: 'SD'}, 
              { title: 'Suriname', label: 'Suriname', value: 'SR'}, 
              { title: 'Svalbard and Jan Mayen', label: 'Svalbard and Jan Mayen', value: 'SJ'}, 
              { title: 'Swaziland', label: 'Swaziland', value: 'SZ'}, 
              { title: 'Sweden', label: 'Sweden', value: 'SE'}, 
              { title: 'Switzerland', label: 'Switzerland', value: 'CH'}, 
              { title: 'Syrian Arab Republic', label: 'Syrian Arab Republic', value: 'SY'}, 
              { title: 'Taiwan, Province of China', label: 'Taiwan, Province of China', value: 'TW'}, 
              { title: 'Tajikistan', label: 'Tajikistan', value: 'TJ'}, 
              { title: 'Tanzania, United Republic of', label: 'Tanzania, United Republic of', value: 'TZ'}, 
              { title: 'Thailand', label: 'Thailand', value: 'TH'}, 
              { title: 'Timor-Leste', label: 'Timor-Leste', value: 'TL'}, 
              { title: 'Togo', label: 'Togo', value: 'TG'}, 
              { title: 'Tokelau', label: 'Tokelau', value: 'TK'}, 
              { title: 'Tonga', label: 'Tonga', value: 'TO'}, 
              { title: 'Trinidad and Tobago', label: 'Trinidad and Tobago', value: 'TT'}, 
              { title: 'Tunisia', label: 'Tunisia', value: 'TN'}, 
              { title: 'Turkey', label: 'Turkey', value: 'TR'}, 
              { title: 'Turkmenistan', label: 'Turkmenistan', value: 'TM'}, 
              { title: 'Turks and Caicos Islands', label: 'Turks and Caicos Islands', value: 'TC'}, 
              { title: 'Tuvalu', label: 'Tuvalu', value: 'TV'}, 
              { title: 'Uganda', label: 'Uganda', value: 'UG'}, 
              { title: 'Ukraine', label: 'Ukraine', value: 'UA'}, 
              { title: 'United Arab Emirates', label: 'United Arab Emirates', value: 'AE'}, 
              { title: 'United Kingdom', label: 'United Kingdom', value: 'GB'}, 
              { title: 'United States', label: 'United States', value: 'US'}, 
              { title: 'United States Minor Outlying Islands', label: 'United States Minor Outlying Islands', value: 'UM'}, 
              { title: 'Uruguay', label: 'Uruguay', value: 'UY'}, 
              { title: 'Uzbekistan', label: 'Uzbekistan', value: 'UZ'}, 
              { title: 'Vanuatu', label: 'Vanuatu', value: 'VU'}, 
              { title: 'Venezuela', label: 'Venezuela', value: 'VE'}, 
              { title: 'Viet Nam', label: 'Viet Nam', value: 'VN'}, 
              { title: 'Virgin Islands, British', label: 'Virgin Islands, British', value: 'VG'}, 
              { title: 'Virgin Islands, U.S.', label: 'Virgin Islands, U.S.', value: 'VI'}, 
              { title: 'Wallis and Futuna', label: 'Wallis and Futuna', value: 'WF'}, 
              { title: 'Western Sahara', label: 'Western Sahara', value: 'EH'}, 
              { title: 'Yemen', label: 'Yemen', value: 'YE'}, 
              { title: 'Zambia', label: 'Zambia', value: 'ZM'}, 
              { title: 'Zimbabwe', label: 'Zimbabwe', value: 'ZW'} 
            ]
        }
    }
}
</script>